# Generated by Django 2.1.3 on 2018-11-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headimage',
            field=models.FileField(default='upload/1.jpg', upload_to='upload/'),
        ),
    ]
